#ifndef __SubGUIClass__
#define __SubGUIClass__

/**
@file
Subclass of GUIClass, which is generated by wxFormBuilder.
*/

#include "GUIClass.h"
#include <map>
#include<vector>
//// end generated include

/** Implementing GUIClass */
class SubGUIClass : public GUIClass
{
	protected:

		static int board[9];
		std::map<int, int> boardPos = {
			{-202, 0},
			{-203, 1},
			{-204, 2},
			{-205, 3},
			{-206, 4},
			{-207, 5},
			{-208, 6},
			{-209, 7},
			{-210, 8},
		};
		enum team {none=0, broth=1, soup=2, tie=3};

		team currentTurn = broth;



		// Handlers for GUIClass events.
		void ButtonPress( wxCommandEvent& event );
		void ResetGame( wxCommandEvent& event );
		void ExitProgram( wxCommandEvent& event );
		

		//My own made functions
		wxStatusBar* findStatusBar();
		int WinnerCheck(); //This int will be checked back agaisnt the enums
		std::vector<int> emptySlots();
		wxBitmap scaleImage(wxString path);
	public:
		/** Constructor */
		SubGUIClass(wxWindow* parent);
		void InitializeGame();
	//// end generated class members
	
};

#endif // __SubGUIClass__
